description = "Your fresh alternative for your IT consulting!"
images = ["logo.png"]
showPostSummary = true
startPageColumns = true
showListsGrouped = true
# alwaysExpandMenu = true
customDateFormat = "02.01.2006"
# hideReadingTime = true
themeColor="blue" # dark, light, blue, do not set for bootstrap default
# js=["/js/test_site.js"]
# css=["/css/test_site.css"]
# csscdn=["https://fonts.googleapis.com/css?family=Concert+One|Roboto&display=swap"]
