# Coding Communities
github           = "jbouse"
gitlab           = "jbouse"
stackoverflow    = "286814" # User Number
bitbucket        = "jbouse"
jsfiddle         = ""
codepen          = ""
# Visual Art Communities
deviantart       = ""
flickr           = ""
behance          = ""
dribbble         = ""
# Publishing Communities
wordpress        = ""
medium           = ""
# Professional/Business Oriented Communities
linkedin         = "jtbouse"
linkedin_company = ""
foursquare       = ""
xing             = ""
slideshare       = ""
# Social Networks
facebook         = "" # https://fb.me/flowartsde
googleplus       = ""
reddit           = ""
quora            = ""
youtube          = "" 
vimeo            = ""
whatsapp         = "" # WhatsApp Number
instagram        = ""
tumblr           = ""
twitter          = ""
skype            = ""
snapchat         = ""
pinterest        = ""
telegram         = ""
discord          = "" # invite link
# Email
email            = "support@UnderGrid.services"
