version: 0.2
 
phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - echo Installing hugo...
      - curl -L -o hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.128.0/hugo_extended_0.128.0_Linux-64bit.tar.gz
      - tar xvfz hugo.tar.gz hugo
      - ./hugo version

  pre_build:
    commands:
      - echo Installing source dependencies...
      - git submodule init
      - git submodule update

  build:
    commands:
      - echo Running Hugo...
      - ./hugo --gc --enableGitInfo --minify

artifacts:
  files:
    - '**/*'
  base-directory: public
