baseURL = "https://undergrid.services"
languageCode = "en-us"
title = "UnderGrid Network Services"
theme = "bootstrap-bp"

# author = "Jeremy T. Bouse"
copyright = "Jeremy T. Bouse"
# googleAnalytics = "UA-2819624-1"
enableRobotsTXT = true
pygmentsCodeFences = true
canonifyurls = true
paginate = 3
enableGitInfo = true

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    post = "/:year/:month/:slug/"
    pages = "/:slug/"
    page = "/:slug/"

[Author]  
  name = "Jeremy T. Bouse"

[params]
  description = "Your fresh alternative for your IT consulting!"
  images = ["logo.png"]
  showPostSummary = true
  startPageColumns = true
  showListsGrouped = true
  # alwaysExpandMenu = true
  customDateFormat = "02.01.2006"
  # hideReadingTime = true
  themeColor="blue" # dark, light, blue, do not set for bootstrap default
  # js=["/js/test_site.js"]
  # css=["/css/test_site.css"]
  # csscdn=["https://fonts.googleapis.com/css?family=Concert+One|Roboto&display=swap"]

[social]
  # Coding Communities
  github           = "jbouse"
  gitlab           = "jbouse"
  stackoverflow    = "286814" # User Number
  bitbucket        = "jbouse"
  jsfiddle         = ""
  codepen          = ""
  # Visual Art Communities
  deviantart       = ""
  flickr           = ""
  behance          = ""
  dribbble         = ""
  # Publishing Communities
  wordpress        = ""
  medium           = ""
  # Professional/Business Oriented Communities
  linkedin         = "jtbouse"
  linkedin_company = ""
  foursquare       = ""
  xing             = ""
  slideshare       = ""
  # Social Networks
  facebook         = "" # https://fb.me/flowartsde
  googleplus       = ""
  reddit           = ""
  quora            = ""
  youtube          = "" 
  vimeo            = ""
  whatsapp         = "" # WhatsApp Number
  instagram        = ""
  tumblr           = ""
  twitter          = ""
  skype            = ""
  snapchat         = ""
  pinterest        = ""
  telegram         = ""
  discord          = "" # invite link
  # Email
  email            = "support@UnderGrid.services"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
    pre = "<i class='fas fa-heart'></i>"

  [[menu.main]]
    identifier = "blog"
    name = "Posts"
    url = "/post/"
    weight = 10
    pre = "<i class='fas fa-blog'></i>"

  [[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
    pre = "<i class='fas fa-address-card'></i>"

  [[menu.footer]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 20
    pre = "<i class='fas fa-folder'></i>"

  [[menu.footer]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
    pre = "<i class='fas fa-tags'></i>"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
